name: work

on: push

jobs:
  user_accetence:
    runs-on: ubuntu-latest
    steps:
      - name: download code 
        uses: actions/checkout@v4

      - name:  set up enviroment
        uses:  actions/setup-node@v4
        with: 
          node-version: 24
          cache: npm


      - name: install depedency
        run: npm ci
        
      - name: build
        run : npm run build

      - name:  create build
        uses: actions/upload-artifact@v4
        with: 
          name: deploy
          path: dist
          retention-days: 7



      