name: Run My Existing Code

on:
  workflow_dispatch:
  push:
    branches: ["master"]

jobs:
  run-code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Run Code
        run: node index.js
